packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  pg@*:
    dependencies:
      pg-native: '*'

yarnPath: .yarn/releases/yarn-berry.cjs
