version: '3.9'

services:
  server:
    build: .
    container_name: kubernetes-cloud-server
    env_file: .env
    image: kubernetes-cloud-server:latest
    # restart: always
    ports:
      - $PORT:$PORT
    # volumes:
    #   - 'server-volume:/server'
# volumes:
#   server-volume:
