version: '3.9'

services:
  server:
    build: .
    container_name: node-template-2021-container
    env_file:
      - .env
    image: node-template-2021-image:latest
    restart: always
    ports:
      - $PORT:$PORT
    # volumes:
    #   - 'server-volume:/server'
# volumes:
#   server-volume:
